version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: scheduler_user
      POSTGRES_PASSWORD: scheduler_pass
      POSTGRES_DB: scheduler_db
    ports:
      - "5432:5432"                # host:container â†’ use 5433 on host to avoid conflicts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/01_init_schema.sql

volumes:
  postgres_data:
